language: node_js
node_js:
  - "lts/*"
  - "8"
  - "10"
  - "12"
sudo: false
cache:
  yarn: true
before_install:
  - npm install --global yarn
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn test-coverage
after_script:
  - npm install --global codecov coveralls
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codecov
